### ISSUE TITLE
Group 2: Tripal Chado SCHEMA API

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#50]
This issue was originally used for a small set of miscellaneous functions which need upgrading. That has been moved to #122 and this issue has been re-assigned for the discussion of the Chado Schema API. This was done since the Chado Schema API did not have a dedicated issue and @guignonv started a good discussion here.

**ONLY discuss the Chado Schema API here. This should not include information on querying the Chado database which is a separate but related issue.**

**Comment by guignonv** [comment]
I think this API should be part of [Drupal\tripal_chado\api\ChadoSchema](https://github.com/tripal/t4d8/blob/9.x-4.x/tripal_chado/src/api/ChadoSchema.php) class. Any function in tripal_chado.api.inc should just call a ChadoSchema method, either static or non-static.

ChadoSchema should provide static functions for almost everything we need to work with a database and it would also provide non-static functions for operations that are (or could be) specific to a given schema (with a known version).

I would see static functions with a prefix "Schema" to let the developer know that he/she will have to provide a schema name to work on. Non-static functions will operate on a specific schema provided when a ChadoSchema object is instantiated.

Furthermore, Drupal\tripal\Services\bulkPgSchemaInstaller also contains things that should be in ChadoSchema in my opinion.

Here is my detailed analysis with some questions and elements to discuss. I would be very happy if other core developers would reply on some or all those points. I've already started to implement some parts and if most people agree, I could manage those major changes and adjust calling code.

ChadoSchema **Static** functions:
- **`protected static function getDatabase(&$db_name)`**:
  internal function to get a database connection object (ie.
  `Drupal::database()`). Static methods will need to get a connection and they
  can't use `$this->connection` (non-static). The `$db_name` parameters let the
  developer specify a database if needed and when not specified he/she will get
  back the actual database name used (obviously 'default'). In the future, we
  could add a hook there to let other module alter the database returned
  according to a given context. For instance, a flag that says current user has
  access to private data and should use a private database instead of the public
  one. ...whatever.

- **`public static function testMode(?bool $test_mode = NULL)`**: this accessor
  can be used as a switch to enable/disable test mode on the API. Test mode
  allows to work on test schema names (that should be protected otherwise) and
  I'm quite sure we will need at one time or another to have a different
  behavior in test mode for some functions.

- **`public static function generateTestSchema(string $version = '1.3')`**:
  generates a new Chado schema for running (automated) tests. In order to be
  efficient, I would have this function create a "template" schema if it does
  not exist first. Then, that schema would be cloned (fast) into a new schema.
  The template schema would be only (re)created when missing so we don't wast
  time processing an SQL file and initializing the database with basic stuff.
  Futhermore, a template schema could be customized, updated and include test
  datasets. I would see template schemas named "_chado_13_test",
  "_chado_14_test",...

- **`public static function cloneSchema(string $source_schema, string $target_schema)`**:
  Clone a given schema by calling `tripal_clone_schema()` PostgreSQL function.

- **`public static function isInvalidSchemaName(string $schema_name)`**:
  Returns an error message explaning why the schema name is not valid or an
  empty string if it's ok. It can be used this way:
  ```
  $issue = isInvalidSchemaName('some name');
  if ($issue) {...}
  ```

- **`public static function quotePgObjectId(string $object_id) {`**: 
  Used to quote a postgreSQL object if it needs it in order to use the returned
  name in queries. It is useful when a schema name contains special characters
  and should be used in a query to prefix a table for instance.

- **`public static function getChadoSchemaDef(string $version = '1.3')`**:
  Returns a structure (from a YAML file) of Chado at the given version in Drupal
  database API format.

- **`public static function findSchemaChadoVersion(string $schema_name = 'chado', string $db_name = '')`**:
  Returns the detected version of a given Chado schema. FALSE if not Chado, 0 if
  version can not be determined, '1.0', '1.1x', '1.2x' '1.3x', '1.4+' otherwise.
  The returned version must always start by a number so it can be tested against
  numeric values (ie. ">= 1.2").

- **`public static function getSchemaTables(string $schema_name, array $include = [], string $db_name = '')`**:
  Returns an array of tables (and views) in the given schema. It can be used by
  modules to find custom tables for instance or check for many tables without
  calling `checkSchemaTableExists()` several times.
  Maybe the returned structure should be improved with more information (it
  currently returns a 'type' property but we could add a 'base' boolean for
  Chado "base" tables, and more).

- **`public static function getSchemaTableDdl(string $table_name, string $schema_name=  'chado', string $db_name = '')`**:
  Returns the SQL code used to create a table in a single string. It's a
  multi-line string that includes the `"CREATE TABLE"` statement as well as
  `"CREATE INDEX"` statements.

- **`public static function parseSchemaTableDdl(string $table_ddl)`**:
  Parses a string returned by `getSchemaTableDdl()` and returns a PHP structure
  that will be more easy to process for other tasks.

- **`public static function getChadoSchemaTableDef(string $table_name, string $version = '1.3')`**:
  Returns a Drupal Schema API structure of a given table from static YAML
  (ie. Chado specifications).

- **`public static function getSchemaTableDef(string $table_name, string $schema_name=  'chado', string $db_name = '')`**:
  Returns a Drupal Schema API structure of a given existing table from its
  real structure.

- **`public static function checkSchemaExists(string $schema_name, string $db_name = '')`**:
  Tells if a given schema exists.

- **`public static function checkSchemaTableExists(string $table_name, string $schema_name = 'chado', string $db_name = '')`**:
  Tells if a given table or view exists. The type is returned (as a TRUE value).

- **`public static function checkSchemaColumnExists(string $table_name, string $column_name, string $schema_name = 'chado', string $db_name = '')`**:
  Tells if a given column exists.

- **`public static function checkSchemaSequenceExists(?string $table_name = NULL, ?string $column_name = NULL, ?string &$sequence_name = NULL, string $schema_name = 'chado', string $db_name = '')`**:
  Tells if a given sequence exists.

- **`public static function checkSchemaIndexExists(string $table_name, ?string &$columns = NULL, ?string $index_name = NULL, string $schema_name = 'chado', string $db_name = '', bool $return_array = FALSE)`**:
  Tells if a given index exists.

- **`public static function checkSchemaFunctionExists(string $function_name, string $function_parameters, string $schema_name = 'chado', string $db_name = '')`**:
  Tells if a given function (or aggregate function) exists.

- **`public static function getSchemaTableDependencies(string $schema_name = 'chado', string $db_name = '')`**:
  Returns a structure describbing all the table dependencies in a given schema.
  I planed to use this function during the Chado upgrade process but I found a
  better way and ended up without using this function. But since the code was
  there, I didn't want to drop it.

Maybe a couple of other static functions should be added (rename schema, remove
schema, check integrity, compare schema, ...?). To discuss.

ChadoSchema **Non**-static functions. The following are already part of the class and I just
add some comments:

- **`public function __construct($version = NULL, $schema_name = NULL)`**:
  Constructor. It defines the "current" Chado schema to use in non-static
  member functions (methods). It also gets the Chado schema version.
  To fix: $version should not be a parameter here. We want to instanciate an
  object that reflects an existing schema (in my opinion) and we should not
  use a ChadoSchema object with an unexisting schema that would be created at
  the given $version after object instanciation. Otherwise, we could call some
  methods that need an existing schema on a missing schema and have an
  unexpected behavior or errors thrown.
  Also, the version number should be obtained using static method
  `findSchemaChadoVersion()`.

- **`public function getVersion()`**:
  Returns Chado version of current schema.
  To fix: maybe a parameter should be added to refresh member variable in case
  the schema has been upgraded and the upgrade result is checked.
  
- **`public function getSchemaName()`**:
  Returns the name of current Chado schema.
  To fix: rename to getName() to avoid confusion with static methods using
  "Schema" in the name to remind they need a "schema name" parameter.

- **`public function getTableNames($include_custom = FALSE)`**:
  What is it used for?
  To fix: Could it rely on static function `getSchemaTables()`? The returned
  keys are the table names.

- **`public function getTableSchema($table)`**:
  Does a similar job as `getSchemaTableDef()`.
  Since this function uses `getSchemaDetails()` which gets the table structure
  from a flat file, it should be turned into a static function as it is not
  related to a specific schema. Should it be better if the table structure would
  be obtained from the database instead? In fact, it is confusing as we don't
  know where the structure comes from: database or static file? Should we
  provide a parameter to select database or flat file? or 2 distinct methods
  with appropriate names?
  To fix: replace this function by a new one called `getTableDef()` that would
  get the structure from the database. If one needs the official Chado
  specifications, he/she would call `getChadoSchemaTableDef()`.

- **`public function getCustomTableSchema($table)`**:
  Unlike `getTableSchema()`, it gets the table structure from the database, but
  from a static record in the database. I believe this information is or will be
  provided by the user in first place, to integrate the table in Tripal. Once
  again, I fill it confusing since it is not computed from the "real" table.
  It would be a good feature to be abled to get the table structure from both
  the database record and the database real structure in order to check table
  integrity for instance, or also being able to upgrade the table (or see if it
  needs to be upgraded) if it is managed by an extension module for instance.
  To fix: replace this function by 2 functions: `getCustomTableDef()` that gets
  the table structure from database and a function `getCustomTableOriginalDef()`
  that would return what has been entered statically in tripal_custom_tables
  by the user or a module.

- **`public function getBaseTables()`**:
  What are the use cases? Is it related to Drupal views to provide view
  handlers? 

- **`public function getSchemaDetails()`**:
  Works on a flat YAML file.
  To fix: Should be static and replaced by `getChadoSchemaDef()`.

- **`public function checkTableExists($table)`**:
  To fix: should use `checkSchemaTableExists()`.

- **`public function checkColumnExists($table, $column)`**:
  To fix: should use `checkSchemaColumnExists()`.

- **`public function checkColumnType($table, $column, $expected_type = NULL)`**:
  What are the use cases? I would remove that. We can get column types from
  `getTableDef()` (getTableSchema()) and put the comparison logic in the caller.

- **`public function checkSequenceExists($table, $column, $sequence_name = NULL)`**:
  To fix: should use `checkSchemaSequenceExists()`.

- **`public function checkPrimaryKey($table, $column = NULL)`**:
  What are the use cases? See `checkColumnType()` comment.
  
- **`public function checkConstraintExists($table, $constraint_name, $type)`**:
  What are the use cases? See `checkColumnType()` comment.

- **`public function checkFKConstraintExists($base_table, $base_column)`**:
  What are the use cases? See `checkColumnType()` comment.

- **`public function checkIndexExists($table, $name, $no_suffix = FALSE)`**:
  To fix: should use `checkSchemaIndexExists()`.

- **`public function addIndex($table, $name, $fields, $no_suffix = FALSE)`**:
  What are the use cases? I would remove that function.


Regarding **tripal_chado.schema.api.inc** functions, I believe most of these functions are
here for "backward compatibility" and/or facilitate code migration. Maybe a
warning should be generated in the logs to let know that those functions are
deprecated?

- **`function chado_table_exists($table, $chado_schema = NULL)`**:
  To fix: should use `ChadoSchema::checkSchemaTableExists()`.

- **`function chado_column_exists($table, $column, $chado_schema = NULL)`**:
  To fix: should use `ChadoSchema::checkSchemaColumnExists()`.

- **`function chado_sequence_exists($sequence, $chado_schema = NULL)`**:
  To fix: should use `ChadoSchema::checkSchemaSequenceExists()`.

- **`function chado_index_exists($table, $name, $no_suffix = FALSE, $chado_schema = NULL)`**:
  To fix: should use `ChadoSchema::checkSchemaIndexExists()`.

- **`function chado_add_index($table, $name, $fields, $chado_schema = NULL)`**:
  Still used?

- **`function chado_is_invalid_schema_name($chado_schema)`**:
  Use `ChadoSchema::isInvalidSchemaName()`.

- **`function chado_dbschema_exists($chado_schema)`**:
  To fix: should use `ChadoSchema::checkSchemaExists()`.

- **`function chado_get_schema_name($schema = 'chado')`**:
  This function was not designed to work with multiple chado instances. Maybe,
  we need a mecanism to get an active schema? Maybe we don't want/need an
  "active" schema and we want to work with several schema at the same time.
  Then, this function may not make sense. I think I asked for it in previous
  versions when Tripal was not supporting multiple chado schema. At that time,
  Tripal would only work with one Chado instance at a time and we could have the
  notion of an "active" Chado schema. Now, it has to be discussed.

- **`function chado_get_installed_schemas()`**:
  It is used by the Chado installation form.
  To fix: It should be moved into ChadoSchema class as a static method.

- **`function chado_get_available_schemas()`**:
  To fix: I added that one but is should be moved into ChadoSchema class as a
  static method as well.

- **`function chado_is_local($force_recheck = FALSE, $chado_schema = NULL)`**:
  To fix: It should be moved to ChadoSchema class as a non-static method that
  would see the database used. Not sure of the uses cases though.

- **`function chado_is_installed($chado_schema = NULL)`**:
  To fix: how about using the ChadoSchema version of
  `chado_get_installed_schemas()` instead? An empty list would mean "no".

- **`function chado_get_version($exact = FALSE, $warn_if_unsupported = FALSE, $chado_schema = NULL)`**:
  To fix: should use `ChadoSchema::findSchemaChadoVersion()`. Arguments differ
  but I don't see a use case where we would need the "exact" version and if
  we call that function, the called can warn if it needs to (ie. it is not the
  job of that function but rather what it is used for).

- **`function chado_get_table_names($include_custom = NULL, $chado_schema = NULL)`**:
  To fix: should use `ChadoSchema::getSchemaTables()` (instead of
  `ChadoSchema::getTableNames()`). About custom tables: what are the use cases?

- **`function chado_get_schema($table, $chado_schema = NULL)`**:
  To fix: should use `ChadoSchema::getChadoSchemaDef()` (instead of
  `ChadoSchema::getTableSchema()`).

- **`function chado_get_custom_table_schema($table, $chado_schema = NULL)`**:
  Depends on `ChadoSchema::getCustomTableSchema()`.

- **`function chado_get_base_tables($chado_schema = NULL)`**:
  Depends on `ChadoSchema::getBaseTables()`.


Now regarding **Drupal\tripal\Services\bulkPgSchemaInstaller** class. I don't understand why we
have this class in Tripal module while it works on Chado and should be part of
Tripal Chado module.
Top fix: this class should be removed and replaced by a new class
\Drupal\tripal_chado\Services\ChadoManager. Most of the current methods should
be moved to ChadoSchema (and renamed). The manager would then use one or more
ChadoSchema instances depending its tasks (ie. derivated manager class).
As far as I understood, the purpose of bulkPgSchemaInstaller (ie. what I call
the "manager") was to provide services. It has been initially designed for
Chado installation but it's too restrictive. When this class is extended, new
methods are added to perform tasks different from the installation. The service
consumer will have specific code to run each service. Furthermore,
bulkPgSchemaInstaller contains members that are also not generic and specific to
an installation service. What I would see in a ChadoManager base service would
be quite simple: a constructor that takes an array as argument, and a couple of
generic functions such as "performAction()" that would do the job the extending
class has been designed for, and "getLogs()" or "getStatus()" or
"getProgress()"...
The constructor would get all the needed parameters from the $args argument
array. If one parameter is missing or incorrect, the constructor would throw an
exception.
The behavior of performAction() would be to first set a lock on the action to
perform in order to avoid conccurent actions. We need to design (or use
existing stuff for that job) a lock mecanims that would prevent an action to be
runned several times concurrently or to have concurrent actions that would make
them fail. For instance, if I started to clone a schema "alpha", I don't want to
have it "upgraded" at the same time: I would have part of it from an old version
and others from an upgraded version.
The other functions would be here for diagnostics. It depends what we want to
achieve. For instance, the "getProgress()" method could be used to get the
current progress in percent of another instance of a manager running its actions
with the same parameters (and class). It could be useful for user feedback
either form the web UI with batch jobs or from command line to get the progress.
Note: we can not use an interface for ChadoManager since we have some common
logic in performAction() that should be used in extending classes.

**Comment by laceysanderson** [comment]
First off, thanks for the lengthy design plan @guignonv and the offer of implementation! You will have noticed I changed the issue description/title since the original issue was not meant for schema discussion and I wanted to re-assign it to preserve your discussion.

# Overall Comments, Thoughts + Suggestions

- The ChadoSchema class in t4d8 was meant to be a straight port of the original one in t3d7 and that is why it is the way it is. It is not yet ideal by any means.
- You would get faster comments @guignonv if you use headers in your design documents. As it is your comment is extremely overwhelming and requires a lot of time to go through and answer. With separate sections and perhaps a summary it would be easier to give more timely feedback as I could focus on one section at a time :-)
- If we are going to overhaul this class now, we need to re-write it to be a [Drupal Service](https://www.drupal.org/docs/drupal-apis/services-and-dependency-injection/services-and-dependency-injection-in-drupal-8) to fit in the new paradigm. This allows for:
   - dependency injection of the schema into Chado query functionality
   - extension modules to replace the default Chado schema implementation as needed
   - efficient caching and performance improvements in general
   - better integration with the new Drupal 8/9 paradigm
- We don't remove functionality originally provided in the Tripal 2/3 functions. All parameters supported in tripal_chado.schema.api.inc functions must make it into the new service (with a default if we don't see it being used as much anymore).
- In places where you asked for use cases, I am not providing them here as I don't have the mental bandwidth or time right now... they need to be kept for backwards compatibility.

## ChadoSchema Service design

- I love the details here but unfortunately don't have a lot of time to go through them in the detail-oriented way I would like but will point out some things that jumped out at me. I will revisit the details in the future.
- The database object should be managed through dependency injection for the service. Static functions should use the Drupal method for getting a database connection in status methods (ie.
Drupal::database() ) rather then wrapping this functionality.
- Please provide further information on why you feel the need for so many static methods. I would make all those requiring the schema name as non-static methods... 
- Most of these methods do not take into account backwards compatibility in parameters... We should not lose any functionality we had before for backwards compatibility.
- I'm really on the fence about providing the full DDL to outside callers... perhaps these should be protected or private methods and the schema API should actually execute the DDL.
- I agree there is some confusion about whether the schema definitions are coming from the official Chado spec or the database itself... we definitely need to make this more clear. However, I think a single function should do both and just have a parameter to make it clear.
- We need to support an active/default Chado schema for backwards compatibility. MOST Tripal sites do not need or want multiple schemas and we don't want to overcomplicate the use of Tripal for the core use case.
- The constructor indicates/sets the Chado schema with which the application currently wants to interact with. I see your point here regarding the $version parameter however there is the use case where you don't care about a specific Chado schema instance but rather want the official information... perhaps we should provide static functions to access non-instance-specific information such as the official table definition... this requires further thought but I am out of time :-(

## Original Chado Schema API from Tripal 2/3 (tripal_chado.schema.api.inc functions)

> Regarding tripal_chado.schema.api.inc functions, I believe most of these functions are
here for "backward compatibility" and/or facilitate code migration. Maybe a
warning should be generated in the logs to let know that those functions are
deprecated?
> ~Valentin

Yes, you are correct, MOST of these functions were included for backwards compatibility. I agree that a deprecation notice should be added.

 - chado_add_index: this is used by extension modules that need to add indices to Chado for improved, instance-specific performance modifications.
 - chado_get_schema_name: we do need a mechanism for an active/default schema to keep backwards compatibility and make usage easier for sites that don't need or want multiple schemas. Since we have a short amount of time to finish this upgrade, we should stick to an active/default model and can discuss the ability to work with multiple concurrent schemas at a later date.
 - chado_is_local: this is needed so Tripal and extension modules know whether they can improve performance through joins between schema (they can if it's local; i.e. within the same PostgreSQL database). 
 - the various checks for indices, etc are needed to check Chado compliance to the official schema. This helps immensely when debugging Tripal as we can rule out weird modifications to the schema.

## Regarding installation

I don't have a lot of time to go into this right now but hope to revisit later. The Drupal\tripal\Services\bulkPgSchemaInstaller is in Tripal to support the installation of non-Chado schemas by centralizing common functionality. Let's revisit the design of the installer after finish the already extensive proposed changes.

**Comment by guignonv** [comment]
Thanks @laceysanderson  for your useful feedback. I will see what I can do in the direction of a  Drupal Service while keeping what's needed for backward compatibility. I've already written some code to manage concurrent access to Chado schemas. I'm currently struggling with Drupal unit tests system. I'll have to do (continue) some more readings/learning and make a new design proposal compatible with old stuff to handle Chado schemas.
We should have a chat about that stuff one day or another before the end of the year. However, I fear I'll have to focus on another project soon... :-s

**Comment by guignonv** [comment]
After a lot of readings, thoughts and code trials, here are some answers.

###  ChadoSchema Service design

>     The database object should be managed through dependency injection for the service. Static functions should use the Drupal method for getting a database connection in status methods (ie.
>     Drupal::database() ) rather then wrapping this functionality.
> 

I wanted to wrap that because we may (want to) support schemas on different databases. Drupal::database() will return the Drupal connection while a different connection may be needed if working on a different database specified in Drupal setting.php file. But it might not be the best approach so I'll think of a better one.

>     Please provide further information on why you feel the need for so many static methods. I would make all those requiring the schema name as non-static methods...

I was thinking "procedural" and not full-OO. The definition of a ChadoSchema object would mean, in my mind, that it is instantiated on a specific Chado schema. So, if you wanted to check the existence of 20 Chado schemas, a non-static "schemaExists" method would mean instantiating 20 ChadoSchema objects. :) Not fun and not efficient. Maybe a "setSchema" method would simplify this, so a single instance could check the existence of any schema? It needs further development.

>     Most of these methods do not take into account backwards compatibility in parameters... We should not lose any functionality we had before for backwards compatibility.

In my opinion, the point here, would be to draw a new API almost form scratch that would be better thought, built on our experiences and needs. Then, a backward-compatible API should be added to complete missing things (or incompatible things) and that one, would rely on the new API or wrap its functions. So we would keep a complete and deprecated old API to simplify the work of moving old D7 stuff to D9 but at the same time we would build on something clean that would follow the new paradigms and be easier to maintain.

>     I'm really on the fence about providing the full DDL to outside callers... perhaps these should be protected or private methods and the schema API should actually execute the DDL.

Good. :-)

>     I agree there is some confusion about whether the schema definitions are coming from the official Chado spec or the database itself... we definitely need to make this more clear. However, I think a single function should do both and just have a parameter to make it clear.

Why not. It doesn't sound like bad idea. It should be discussed to see how we would uses this.

>     We need to support an active/default Chado schema for backwards compatibility. MOST Tripal sites do not need or want multiple schemas and we don't want to overcomplicate the use of Tripal for the core use case.

I agree. I see several approaches to discuss. A first one would be:

- if only one instance of Chado is installed, problem solved.
- if more than one instance is installed, the UI should propose to select a default one (in config API).
- Plugins/extensions should be able to modify the default schema on-the-fly according to some context.
- How about using multiple Chado instances on a same page? Maybe that complexity should be "hidden" by default in Tripal Chado by using a default schema but an extension module should be able to add the required UI (and API?) to manage multiple instances.

>     The constructor indicates/sets the Chado schema with which the application currently wants to interact with. I see your point here regarding the $version parameter however there is the use case where you don't care about a specific Chado schema instance but rather want the official information... perhaps we should provide static functions to access non-instance-specific information such as the official table definition...

It needs more thoughts indeed and also some live discussions. :)


I've started some work on the redesign of some of those things: the Schema API, Chado services, automated tests. How about, in the coming months, you "stabilize" a version of the current code and I port my changes on that as a pull request, to show what will be changed and how? *I'm not done yet* ( https://github.com/guignonv/t4d8/tree/9.x-4.x_Chado_API/tripal_chado ) but I need to see what you will keep and what will be changed in order to adapt my code. I believe the current version I made may bring too many changes on the "legacy" API. In fact, I would need to see what should remain there as "legacy" and what as been added for T4 that could be changed. Maybe legacy functions should be tagged?

**Comment by laceysanderson** [comment]
This is now outdated since the Tripal DBX API was submitted by @guignonv 

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
