### ISSUE TITLE
Updates to All Other Integrations

### ISSUE THREAD

**Issue by shawnawsu** [tripal/t4d8#8]
Please tag all tickets and pr's with group 8 to denote it relates to this group of updates.

Files this update will require to be reviewed and updated (in order):

- [ ] Drush:
    - [ ] tripal.drush.inc
    - [ ] tripal_bulk_loader.drush.inc
    - [ ] tripal_chado.drush.inc
    - [ ] tripal_daemon.drush.inc
- [ ] Collections
    - [ ] tripal.collections.api.inc
    - [ ] Tripal.collections.inc
- [ ] D3js
    - [ ] tripal.d3js.api.inc

**Comment by par12005** [comment]
I updated D3js as part of PR #43, since D3js was required for the Content Type Bar Chart block. From what I could tell, the `tripal_add_d3js()` function simply added the D3 JS library to the page. This can now be achieved by adding `'#attached' => ['library' => ['tripal/d3']]` to your Drupal 8 render array. You can see an example of this in [`tripal/src/Plugin/Block/ContentBarChartBlock::build()`](https://github.com/tripal/t4d8/pull/43/files?file-filters%5B%5D=.php#diff-1efc38067b6badd7a738ed1179125a84)

**Comment by laceysanderson** [comment]
Closing these roadmap issues as we arn't currently using this approach to focus the upgrade. 

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
