### ISSUE TITLE
chado_insert_cvterm() is slow

### ISSUE THREAD

**Issue by laceysanderson** [tripal/t4d8#91]
This issue is to remind us to speed up [chado_insert_cvterm()](https://github.com/tripal/t4d8/blob/9.x-4.x/tripal_chado/src/api/tripal_chado.cv.api.inc#L453). This function is used when creating Tripal Terms and chado cvterms and causes noticeable performance issues. Since Tripal Terms will be created during Installation of every Tripal site, this should be considered a high priority.

**Comment by risharde** [comment]
Initial issue was the unit tests were not working - after a lot of debugging - the issue turned out to be that one must perform the following command on the docker container before running these tests.

`docker exec tripaldocker drush trp-prep-tests`

After removing the "incomplete" lines for the 2 unit tests and testing with the testchado schema existing, the tests completed successfully.

Continuing on to look at how we can improve the performance.

**Comment by laceysanderson** [comment]
Some improvements to performance were done as part of #98 however, adding Tripal Terms is still quite slow and I suspect this function is the culprit. 

Here are some timings on my system for creating a single Tripal Term through the UI. This is noticeably slower then creating vocab/idspaces and updating terms. Updating takes ~1/2 the time on my system according to Firefox developer tools.
<img width="1413" alt="Screen Shot 2021-01-14 at 9 48 00 AM" src="https://user-images.githubusercontent.com/1566301/104775710-6c360300-573e-11eb-92eb-69f6443628dc.png">

**Comment by risharde** [comment]
Wow 15 seconds seems long, I will try to do some further tests but on my
dev it was shorter

**Comment by laceysanderson** [comment]
A lot has changed since this issue was created. I'm closing it since nothing can currently be done and the problem may not even exist after the new API is done. Also this could have been environment dependant.
